#!/usr/bin/env bash
#
# Summary: Do a backup action
#
# Usage: gutbackup backup <profile> [instance] [rsync_options]
#
# [OPTIONS]
#   -d      # directory, default is /backup
#
# Examples:
#
#   gutbackup backup hello
#   gutbackup backup hello system --dry-run
#

set -e
[[ -n "$GUTBACKUP_DEBUG" ]] && set -x

source "$GUTBACKUP_ROOT/libexec/lib.sh"
source "$GUTBACKUP_ROOT/libexec/helpers.sh"

[[ -z "$1" ]] && gutbackup-help --usage backup >&2 && exit 1

# Settings
host=""
dir="/backup"
src="/"
backup_options="--archive --hard-links --acls --xattrs --compress --verbose --human-readable -P --stats --del --delete-excluded --recursive"
# --recursive is for --from-file

main() {
  # handle arguments
  TEMP="${TEMP:-/tmp}"
  profile="$1"; shift
  case "$1" in
    "" | -* ) instance="default" ;;
    * ) instance="$1"; shift ;;
  esac
  extra_rsync_options="$@"
  profile_file="$dir/conf/$profile.conf"            # /backup/conf/hello.conf
  profile_dir="$dir/conf/$profile"                  # /backup/conf/hello/
  instance_file="$profile_dir/$instance"            # /backup/conf/hello/<instance>
  work_dir="$dir/$profile/work"                     # /backup/hello/work

  # source a b
  [[ -e "$profile_file" ]] && source "$profile_file"
  [[ ! -e "$instance_file" ]] && error_exit "gutbackup: instance file does not exists -- $instance_file"
  source "$instance_file"

  # main
  [[ $check_root == true && $(id -u) -ne 0 ]] && error_exit "gutbackup: you cannot perform this operation unless you are root."

  if [[ $(type -t "backup") != "function" ]]; then
    backup() {
      run this
    }
  fi

  mkdir -p "$work_dir"
  cd "$work_dir"
  backup
  cd "$OLDPWD"
}

#####
# DSL
#####

# run this
# run system
run() {
  # handle arguments
  local loc_instance files exclude cmd
  [[ "$1" == "this" ]] && loc_instance="$instance" || loc_instance="$1"
	file="$profile_dir/$loc_instance"

  # source a
	[[ ! -e "$file" ]] && error_exit "gutbackup: file does not exists -- $file"
  source "$file"

  # main
  if [[ ! -z "$files" ]]; then
    echo "$files" > $TEMP/files.gutbackup
    cmd="$cmd --files-from $TEMP/files.gutbackup"
  fi
  if [[ ! -z "$exclude" ]]; then
    echo "$exclude" > $TEMP/exclude.gutbackup
    cmd="$cmd --exclude-from $TEMP/exclude.gutbackup"
  fi
  cmd="$cmd $backup_options $extra_rsync_options $src/ $host$dir/$profile/$loc_instance/"
  say ">> rsync $cmd"
  rsync $cmd
}

main "$@"
